### ISSUE TITLE
Dimension types are inconsistent in the specification

### ISSUE THREAD

**Issue by trickvi** [openspending/fiscal-data-package#56]
From an example in the spec where dimension types are first discussed:

>    # dimensionType is optional
>    # it can be used to indicate this is a standard types e.g. entity, classification, program etc
>    "dimensionType": "...",

Then later in the spec the dimension types are listed (without a description of what they are):

> Dimension Types:
>
> * datetime
> * entity
> * classification
> * project

Note that "program" from the list in the example has been dropped and instead "datetime" and "project" have been introduced. I suspect there's a mix up between "program" and "project" but I don't really understand either of those dimension types (and description is missing) so I don't know which one is the right one and under which circumstances it should be used so I can't make a pull request to fix this.

**Comment by rgrp** [comment]
@trickvi is this fixed by https://github.com/openspending/fiscal-data-package/pull/51? I think it is.

**Comment by trickvi** [comment]
@rgrp No it isn't. I don't know if we're going with ``program`` or ``project`` or both. We still have the example saying "program" and list saying "project".

**Comment by rgrp** [comment]
@trickvi I can't spot the example where we have `program` rather than `project`. Could you help me locate it and then i can fix it :-)

**Comment by trickvi** [comment]
First example in this section: https://github.com/openspending/fiscal-data-package/blob/master/spec/index.md#dimensions

It says

> # it can be used to indicate this is a standard types e.g. entity, classification, program etc
