### ISSUE TITLE
Describing sources inconsistency

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#57]
In "Describing Sources", the pattern for describing sources is described as:
    
    "source": "name-of-field-on-the-resource",
    "resource": "name-of-resource"

Elsewhere, I see examples like:

    "source": "entities/about"
    
and

    "source": "budget/budget"

I assume the pattern was "resource/field", but as there no description of this pattern, I'm guessing it is a holdover from a previous spec?

**Comment by rgrp** [comment]
This is a bug representing a holdover from earlier version of spec. Will fix in examples now.

**Comment by danfowler** [comment]
Fixed in examples 28ffedacdc28375a7def36e9cb9a38f17f7bbd56

**Comment by pwalsh** [comment]
Not fixed:

* https://github.com/openspending/fiscal-data-package/blob/master/examples/entities-normalized/datapackage.json#L94: source should be `id` not `payee_id` and likewise just below source should be `name` and not `payee_name`. Didn't have time to check other changes.

**Comment by rgrp** [comment]
My bad and I will fix.
